sudo: required
dist: trusty
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
language: node_js
node_js:
- '8'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install --quiet -g gulp-cli
script: gulp test:ci
before_deploy:
- yarn run start
- gulp build:demo
- cd dist
deploy:
- provider: npm
  skip_cleanup: true
  on:
    tags: true
    repo: mmjmanders/ngx-iban
  email: mmjmanders@gmail.com
  api_key:
    secure: "qGqdd4UWAnjDEKaX3Z0qz3qKtCYh0ag57L71DQF5XQmbpBS66evFX8S7NjeRIBILM2cViPcAT6aeRKjDwkdpdDCz5mUn7udwjzB+QmmfczFQDn1/X+2HVdoOKUFo5Y1AtHpH6wuV90raolT2RBUxscFGaTSDjnsiEpH3F6G0E854V8ssa5+rci4P3z37FwmyphQENx6YoNXhbnOGnEgPu0hvMzJ+tEu4VuuYEuyzYYOanMx14JEO+NQXYnw8ckfq82hra8wiT/3bTVkDFJE4t8mkkuZALcltXci4SDhVDbPzHiTh4IfqkKgXRhKUmi2ObjuHzv4LE1YUmSFT02Jp284q2jpWWouPoNTk3Z9rKGBYwUeVR4bG01sGhOM+7Nbyx5KVThSaw0SCVOrOekd3oExs+LmnWQdQIjGhIXesAuQHh28SuymM6W7CGjxvnzgUziizPswPHzRDxg6SVo3vjzdTv2hHkBdRtLHiBo5uJmpDgVmC6BH3yCPOG26blSKBg4Hn2yKdWPohniYW6PWh1LngP9pykJR0oTiXUYgiHakNwbgXFk9ZB+u+v669HacOvcnrubxwpRTElxmepMzzEqOZIawjzzehekha/mgB+vRrvA6dtT+POipksevCkhM3NbUAEHHU08rOa1YxBM/H7hFE+CfMSps8Ukh2Dd78FvY="
- provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: demo/dist/browser
after_success: gulp coveralls
cache:
  yarn: true
